export const DISPONIBILITY = "Disponibilidade";
export const ACCESS_CONDITIONS = "Condições de acesso";
export const CONDITIONS = "Condições de reprodução";
export const PROTECTION = "Proteção";
export const PROTECTION_INSTITUTE = "Instituição Protetora";
export const NUMBER_PROCESS = "Nº de processo";
export const RETURN_DATE = "Data de retorno";
export const USE = "Uso e aproveitamento";
export const EMPTY_VALUE = '-';
