CREATE TABLE VERSAOBEMPATRIMONIAL (ID BIGINT NOT NULL, BEM BYTEA, TIMESTAMP BYTEA, BEMPATRIMONIAL_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE VERSAOBEMPATRIMONIAL ADD CONSTRAINT FK_VERSAOBEMPATRIMONIAL_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
CREATE SEQUENCE VERSAOBEMPATRIMONIAL_SEQ START WITH 1;
