CREATE TABLE VERSAOBEMPATRIMONIAL (ID BIGINT NOT NULL, BEMPATRIMONIALBYTES BYTEA, TIMESTAMP TIMESTAMP, BEMPATRIMONIAL_ID BIGINT, USUARIO_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE VERSAOBEMPATRIMONIAL ADD CONSTRAINT FK_VERSAOBEMPATRIMONIAL_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID) ON DELETE CASCADE;
ALTER TABLE VERSAOBEMPATRIMONIAL ADD CONSTRAINT FK_VERSAOBEMPATRIMONIAL_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
CREATE SEQUENCE VERSAOBEMPATRIMONIAL_SEQ START WITH 1;
