CREATE TABLE VERSAOBEMPATRIMONIAL (ID BIGINT NOT NULL, BEMPATRIMONIALBYTES BYTEA, TIMESTAMP TIMESTAMP, BEMPATRIMONIAL_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE VERSAOBEMPATRIMONIAL ADD CONSTRAINT FK_VERSAOBEMPATRIMONIAL_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
CREATE SEQUENCE VERSAOBEMPATRIMONIAL_SEQ START WITH 1;
