CREATE TABLE USUARIO (ID VARCHAR(255) NOT NULL, ADMINISTRADOR BOOLEAN, ATIVO BOOLEAN, EMAIL VARCHAR(255) UNIQUE, NOMECOMPLETO VARCHAR(255), SENHA VARCHAR(255), TELEFONE VARCHAR(255), VALIDADE DATE, PRIMARY KEY (ID));
CREATE TABLE GRUPO (ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ACESSO (VALIDADE BOOLEAN, GRUPO VARCHAR(255) NOT NULL, INSTITUICAO BIGINT NOT NULL, USUARIO VARCHAR(255) NOT NULL, PRIMARY KEY (GRUPO, INSTITUICAO, USUARIO));
CREATE TABLE INSTITUICAO (ID BIGINT NOT NULL, ADMINISTRADORPROPRIEDADE VARCHAR(255), CAIXAPOSTAL VARCHAR(255), CEP VARCHAR(255), CIDADE VARCHAR(255), EMAIL VARCHAR(255), ENDERECO VARCHAR(255), ESTADO VARCHAR(255), IDENTIFICACAOPROPRIETARIO VARCHAR(255), LATITUDE VARCHAR(255), LOCALIDADE VARCHAR(255), LONGITUDE VARCHAR(255), NOME VARCHAR(255), PAIS VARCHAR(255), TELEFONE VARCHAR(255), URL VARCHAR(255), VALIDADE BOOLEAN, PRIMARY KEY (ID));
CREATE TABLE ITEMAUDITORIA (ID BIGINT NOT NULL, ATRIBUTOSIGNIFICATIVO VARCHAR(255), DATA DATE, NOTAS VARCHAR(255), TIPOACAO INTEGER, AUTORACAO_ID VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE AUTOR (ID BIGINT NOT NULL, ATIVIDADE VARCHAR(255), CODINOME VARCHAR(255), NASCIMENTO VARCHAR(255), NOME VARCHAR(255), OBITO VARCHAR(255), SOBRENOME VARCHAR(255), TIPOAUTORIA VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE APROVACAO (ID BIGINT NOT NULL, CHAVEESTRANGEIRA VARCHAR(255), DATA DATE, EXPIRACAO DATE, TABELAESTRANGEIRA VARCHAR(255), APROVADOR VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID);
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO (ID);
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_INSTITUICAO FOREIGN KEY (INSTITUICAO) REFERENCES INSTITUICAO (ID);
ALTER TABLE ITEMAUDITORIA ADD CONSTRAINT FK_ITEMAUDITORIA_AUTORACAO_ID FOREIGN KEY (AUTORACAO_ID) REFERENCES USUARIO (ID);
ALTER TABLE APROVACAO ADD CONSTRAINT FK_APROVACAO_APROVADOR FOREIGN KEY (APROVADOR) REFERENCES USUARIO (ID);
CREATE SEQUENCE APROVACAO_SEQ START WITH 1;
CREATE SEQUENCE AUTOR_SEQ START WITH 1;
CREATE SEQUENCE INSTITUICAO_SEQ START WITH 1;
CREATE SEQUENCE ITEMAUDITORIA_SEQ START WITH 1;
/* Usuario admin padr�o para o desenvolvimento do sistema:
ID:mvirtual
Email:mvirtual@usp.br
senha:mvirtual
*/
INSERT INTO USUARIO values( 'mvirtual', true, true, 'mvirtual@usp.br','Mem�ria Virtual',
'8D1E3B49C3A725414FBED43AD7E0A480DEA6220A83DF3B10C4496270FC5A1E6328732550F4AC8C4F6ADE0EAE7F82DC9CF3219D724E6369AA044FD630B9C5E178',
'(16)7777-7777',
						null);