CREATE TABLE MULTIMIDIA (ID BIGINT NOT NULL, CONTENT BYTEA, CONTENTTYPE VARCHAR(255), DESCRICAO VARCHAR(255), NOME VARCHAR(255), THUMB BYTEA, CONTAINERMULTIMIDIA_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE CONTAINERMULTIMIDIA (ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE INSTITUICAO (ID BIGINT NOT NULL, ADMINISTRADORPROPRIEDADE VARCHAR(255), ALTITUDE VARCHAR(255), CAIXAPOSTAL VARCHAR(255), CEP VARCHAR(255), CIDADE VARCHAR(255), EMAIL VARCHAR(255), ENDERECO VARCHAR(255), ESTADO VARCHAR(255), IDENTIFICACAOPROPRIETARIO VARCHAR(255), LATITUDE VARCHAR(255), LEGISLACAOINCIDENTE VARCHAR(255), LOCALIDADE VARCHAR(255), LONGITUDE VARCHAR(255), NOME VARCHAR(255), PAIS VARCHAR(255), PROTECAOEXISTENTE INTEGER, SINTESEHISTORICA VARCHAR(255), TELEFONE VARCHAR(255), TIPOPROPRIEDADE INTEGER, URL VARCHAR(255), VALIDADE BOOLEAN, CONTAINERMULTIMIDIA_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE BEMPATRIMONIAL_TITULOS (ID BIGINT NOT NULL, TIPO INTEGER, VALOR VARCHAR(255), BEMPATRIMONIAL_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE AUTOR (ID BIGINT NOT NULL, ATIVIDADE INTEGER, CODINOME VARCHAR(255), NASCIMENTO VARCHAR(255), NOME VARCHAR(255), OBITO VARCHAR(255), SOBRENOME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE AUTORIA (ID BIGINT NOT NULL, TIPO INTEGER, BEMPATRIMONIAL BIGINT, AUTOR_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE APROVACAO (ID BIGINT NOT NULL, ACAO INTEGER, ALTERADAEM DATE, CRIADAEM DATE, DADOS VARCHAR(255), EXPIRAEM DATE, STATUS INTEGER, ANALISTA BIGINT, SOLICITANTE BIGINT, PRIMARY KEY (ID));
CREATE TABLE USUARIO (ID BIGINT NOT NULL, ADMINISTRADOR BOOLEAN, ATIVO BOOLEAN, EMAIL VARCHAR(255), IDENTIFICACAO VARCHAR(255), NOMECOMPLETO VARCHAR(255), SENHA VARCHAR(255), TELEFONE VARCHAR(255), VALIDADE DATE, PRIMARY KEY (ID));
CREATE TABLE ASSUNTO (ASSUNTO VARCHAR(255) NOT NULL, PRIMARY KEY (ASSUNTO));
CREATE TABLE GRUPO (ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ACESSO (ID BIGINT NOT NULL, VALIDADE BOOLEAN, GRUPO VARCHAR(255), INSTITUICAO BIGINT, USUARIO BIGINT, PRIMARY KEY (ID));
CREATE TABLE DESCRITOR (DESCRITOR VARCHAR(255) NOT NULL, PRIMARY KEY (DESCRITOR));
CREATE TABLE BEMPATRIMONIAL (ID BIGINT NOT NULL, AGUAPROXIMA VARCHAR(255), ALCOVA BOOLEAN, ALTURA VARCHAR(255), ALTURACUMEEIRA VARCHAR(255), ALTURAFACHADAFRONTAL VARCHAR(255), ALTURAFACHADAPOSTERIOR VARCHAR(255), ALTURATOTAL VARCHAR(255), AREATOTAL VARCHAR(255), CARACTERISTICASAMBIENTAIS VARCHAR(255), CARACTERISTICASFISICASTECNICASEXECUTIVAS VARCHAR(255), COLECAO VARCHAR(255), COMPLEMENTO VARCHAR(255), COMPRIMENTO VARCHAR(255), CONDICAOTOPOGRAFICA VARCHAR(255), CONTEUDO VARCHAR(255), DIMENSOESQUANTIFICACOES VARCHAR(255), EXPOSICAO INTEGER, EXTERNO BOOLEAN, IDMIDIA VARCHAR(255), LARGURA VARCHAR(255), LATITUDE VARCHAR(255), LOCALIZACAOFISICA VARCHAR(255), LONGITUDE VARCHAR(255), MEIOACESSO VARCHAR(255), MEIOANTROPICO VARCHAR(255), NOTAS VARCHAR(255), NUMEROAMBIENTES INTEGER, NUMEROPAVIMENTOS INTEGER, NUMEROREGISTRO VARCHAR(255), OUTROS VARCHAR(255), PEDIREITOTERREO VARCHAR(255), PEDIREITOTIPO VARCHAR(255), PORAO BOOLEAN, PROFUNDIDADE VARCHAR(255), SITIOPAISAGEM VARCHAR(255), SOTAO BOOLEAN, TIPOBEMPATRIMONIAL VARCHAR(255), TITULOPRINCIPAL VARCHAR(255), USO VARCHAR(255), USOATUAL VARCHAR(255), VEGETACAO VARCHAR(255), ESTADOCONSERVACAO INTEGER, ESTADOPRESERVACAO INTEGER, NOTASESTADOCONSERVACAO VARCHAR(255), CONDICOESACESSO INTEGER, CONDICOESREPRODUCAO INTEGER, DATARETORNO VARCHAR(255), DISPONIBILIDADE INTEGER, LEGISLACAO VARCHAR(255), NOTASUSOAPROVEITAMENTO VARCHAR(255), PROTECAO INTEGER, PROTETORAINSTITUICAO VARCHAR(255), DADOSDOCTRANSACAO VARCHAR(255), DATAAQUISICAO VARCHAR(255), HISTORICO VARCHAR(255), INSTRUMENTOPESQUISA VARCHAR(255), PRIMEIROPROPRIETARIO VARCHAR(255), TIPOAQUISICAO INTEGER, VALORVENALTRANSACAO VARCHAR(255), ANO VARCHAR(255), EDICAO VARCHAR(255), LOCAL VARCHAR(255), OUTRASRESPONSABILIDADES VARCHAR(255), INSTITUICAO_ID BIGINT, CONTAINERMULTIMIDIA_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE BEMPATRIMONIAL_ASSUNTO (ASSUNTO_ID VARCHAR(255) NOT NULL, BEMPATRIMONIAL_ID BIGINT NOT NULL, PRIMARY KEY (ASSUNTO_ID, BEMPATRIMONIAL_ID));
CREATE TABLE BEMPATRIMONIAL_DESCRITOR (DESCRITOR_ID VARCHAR(255) NOT NULL, BEMPATRIMONIAL_ID BIGINT NOT NULL, PRIMARY KEY (DESCRITOR_ID, BEMPATRIMONIAL_ID));
CREATE TABLE BEMPATRIMONIAL_INTERVENCOES (DATA VARCHAR(255), DESCRICAO VARCHAR(255), RESPONSAVEL VARCHAR(255), BEMPATRIMONIAL_ID BIGINT);
CREATE TABLE BEMPATRIMONIAL_PESQUISADORES (DATAPESQUISA VARCHAR(255), NOME VARCHAR(255), NOTASPESQUISADOR VARCHAR(255), BEMPATRIMONIAL_ID BIGINT);
CREATE TABLE BEMPATRIMONIAL_FONTESINFORMACAO (BEMPATRIMONIAL_ID BIGINT, FONTESINFORMACAO VARCHAR(255));
CREATE TABLE BEMPATRIMONIAL_BENSRELACIONADOS (BEMPATRIMONIAL_ID BIGINT NOT NULL, BENSRELACIONADOS_ID BIGINT NOT NULL, PRIMARY KEY (BEMPATRIMONIAL_ID, BENSRELACIONADOS_ID));
ALTER TABLE MULTIMIDIA ADD CONSTRAINT FK_MULTIMIDIA_CONTAINERMULTIMIDIA_ID FOREIGN KEY (CONTAINERMULTIMIDIA_ID) REFERENCES CONTAINERMULTIMIDIA (ID);
ALTER TABLE INSTITUICAO ADD CONSTRAINT FK_INSTITUICAO_CONTAINERMULTIMIDIA_ID FOREIGN KEY (CONTAINERMULTIMIDIA_ID) REFERENCES CONTAINERMULTIMIDIA (ID);
ALTER TABLE BEMPATRIMONIAL_TITULOS ADD CONSTRAINT FK_BEMPATRIMONIAL_TITULOS_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE AUTORIA ADD CONSTRAINT FK_AUTORIA_AUTOR_ID FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR (ID);
ALTER TABLE AUTORIA ADD CONSTRAINT FK_AUTORIA_BEMPATRIMONIAL FOREIGN KEY (BEMPATRIMONIAL) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE APROVACAO ADD CONSTRAINT FK_APROVACAO_SOLICITANTE FOREIGN KEY (SOLICITANTE) REFERENCES USUARIO (ID);
ALTER TABLE APROVACAO ADD CONSTRAINT FK_APROVACAO_ANALISTA FOREIGN KEY (ANALISTA) REFERENCES USUARIO (ID);
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO (ID);
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID);
ALTER TABLE ACESSO ADD CONSTRAINT FK_ACESSO_INSTITUICAO FOREIGN KEY (INSTITUICAO) REFERENCES INSTITUICAO (ID);
ALTER TABLE BEMPATRIMONIAL ADD CONSTRAINT FK_BEMPATRIMONIAL_CONTAINERMULTIMIDIA_ID FOREIGN KEY (CONTAINERMULTIMIDIA_ID) REFERENCES CONTAINERMULTIMIDIA (ID);
ALTER TABLE BEMPATRIMONIAL ADD CONSTRAINT FK_BEMPATRIMONIAL_INSTITUICAO_ID FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID);
ALTER TABLE BEMPATRIMONIAL_ASSUNTO ADD CONSTRAINT FK_BEMPATRIMONIAL_ASSUNTO_ASSUNTO_ID FOREIGN KEY (ASSUNTO_ID) REFERENCES ASSUNTO (ASSUNTO);
ALTER TABLE BEMPATRIMONIAL_ASSUNTO ADD CONSTRAINT FK_BEMPATRIMONIAL_ASSUNTO_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_DESCRITOR ADD CONSTRAINT FK_BEMPATRIMONIAL_DESCRITOR_DESCRITOR_ID FOREIGN KEY (DESCRITOR_ID) REFERENCES DESCRITOR (DESCRITOR);
ALTER TABLE BEMPATRIMONIAL_DESCRITOR ADD CONSTRAINT FK_BEMPATRIMONIAL_DESCRITOR_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_INTERVENCOES ADD CONSTRAINT FK_BEMPATRIMONIAL_INTERVENCOES_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_PESQUISADORES ADD CONSTRAINT FK_BEMPATRIMONIAL_PESQUISADORES_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_FONTESINFORMACAO ADD CONSTRAINT FK_BEMPATRIMONIAL_FONTESINFORMACAO_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_BENSRELACIONADOS ADD CONSTRAINT FK_BEMPATRIMONIAL_BENSRELACIONADOS_BEMPATRIMONIAL_ID FOREIGN KEY (BEMPATRIMONIAL_ID) REFERENCES BEMPATRIMONIAL (ID);
ALTER TABLE BEMPATRIMONIAL_BENSRELACIONADOS ADD CONSTRAINT FK_BEMPATRIMONIAL_BENSRELACIONADOS_BENSRELACIONADOS_ID FOREIGN KEY (BENSRELACIONADOS_ID) REFERENCES BEMPATRIMONIAL (ID);
CREATE SEQUENCE APROVACAO_SEQ START WITH 1;
CREATE SEQUENCE BEMPATRIMONIAL_SEQ START WITH 1;
CREATE SEQUENCE MULTIMIDIA_SEQ START WITH 1;
CREATE SEQUENCE INSTITUICAO_SEQ START WITH 1;
CREATE SEQUENCE USUARIO_SEQ START WITH 2;
CREATE SEQUENCE AUTORIA_SEQ START WITH 1;
CREATE SEQUENCE AUTOR_SEQ START WITH 1;
CREATE SEQUENCE TITULO_SEQ START WITH 1;
CREATE SEQUENCE ACESSO_SEQ START WITH 1;
CREATE SEQUENCE CONTAINERMULTIMIDIA_SEQ START WITH 1;
/* Usuario admin padrao para o desenvolvimento do sistema:
ID:mvirtual
Email:mvirtual@usp.br
senha:mvirtual
*/
INSERT INTO USUARIO values(1, true, true, 'mvirtual@usp.br', 'mvirtual', 'Memoria Virtual',
'8D1E3B49C3A725414FBED43AD7E0A480DEA6220A83DF3B10C4496270FC5A1E6328732550F4AC8C4F6ADE0EAE7F82DC9CF3219D724E6369AA044FD630B9C5E178',
'(16)7777-7777',null);

INSERT INTO GRUPO values('CATALOGADOR');
INSERT INTO GRUPO values('REVISOR');
INSERT INTO GRUPO values('GERENTE');

