ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_USUARIO
ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_GRUPO
ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_INSTITUICAO
ALTER TABLE ITEMAUDITORIA DROP CONSTRAINT FK_ITEMAUDITORIA_AUTORACAO_ID
DROP TABLE USUARIO
DROP TABLE GRUPO
DROP TABLE ACESSO
DROP TABLE INSTITUICAO
DROP TABLE ITEMAUDITORIA