----------------
-- DROP TABLE --
----------------

DROP TABLE MULTIMIDIA CASCADE;
DROP TABLE CONTAINERMULTIMIDIA CASCADE;
DROP TABLE INSTITUICAO CASCADE;
DROP TABLE BEMPATRIMONIAL_TITULOS CASCADE;
DROP TABLE AUTOR CASCADE;
DROP TABLE AUTORIA CASCADE;
DROP TABLE APROVACAO CASCADE;
DROP TABLE USUARIO CASCADE;
DROP TABLE ASSUNTO CASCADE;
DROP TABLE GRUPO CASCADE;
DROP TABLE ACESSO CASCADE;
DROP TABLE DESCRITOR CASCADE;
DROP TABLE BEMPATRIMONIAL CASCADE;
DROP TABLE BEMPATRIMONIAL_ASSUNTO CASCADE;
DROP TABLE BEMPATRIMONIAL_DESCRITOR CASCADE;
DROP TABLE BEMPATRIMONIAL_INTERVENCOES CASCADE;
DROP TABLE BEMPATRIMONIAL_PESQUISADORES CASCADE;
DROP TABLE BEMPATRIMONIAL_FONTESINFORMACAO CASCADE;
DROP TABLE BEMPATRIMONIAL_BENSRELACIONADOS CASCADE;

-------------------
-- DROP SEQUENCE --
-------------------

DROP SEQUENCE INSTITUICAO_SEQ;
DROP SEQUENCE BEMPATRIMONIAL_SEQ;
DROP SEQUENCE AUTOR_SEQ;
DROP SEQUENCE MULTIMIDIA_SEQ;
DROP SEQUENCE CONTAINERMULTIMIDIA_SEQ;
DROP SEQUENCE TITULO_SEQ;
DROP SEQUENCE APROVACAO_SEQ;
DROP SEQUENCE USUARIO_SEQ;
DROP SEQUENCE AUTORIA_SEQ;
DROP SEQUENCE ACESSO_SEQ;
DROP SEQUENCE REVISAO_SEQ; 