ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_GRUPO_ID;
ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_USUARIO_ID;
ALTER TABLE ACESSO DROP CONSTRAINT FK_ACESSO_INSTITUICAO_NUMREGISTRO;
DROP TABLE INSTITUICAO;
DROP TABLE GRUPO;
DROP TABLE ACESSO;
DROP TABLE USUARIO;
