<%--
    Document   : sobreMV
    Created on : Mar 24, 2010, 12:42:03 AM
    Author     : paul
--%>

<jsp:include page="../config/header.jsp" />

									<h1>:: O Mem&oacute;ria Virtual</h1>
									<div style="margin: 0in 0in 10pt">&nbsp;O Mem&oacute;ria Virtual &eacute; um sistema web para cataloga&ccedil;&atilde;o e dissemina&ccedil;&atilde;o de informa&ccedil;&otilde;es sobre acervos do patrim&ocirc;nio hist&oacute;rico, cultural e art&iacute;stico. &Eacute; um sistema de software livre licenciado sob a GPL (General Public License).&nbsp;Permite o registro de informa&ccedil;&otilde;es, em uma &uacute;nica base de dados e de forma integrada, de diferentes tipos de acervos hist&oacute;ricos, seja bibliogr&aacute;ficos, museol&oacute;gicos, arquiviol&oacute;gicos, arquitet&ocirc;nicos, naturais e imateriais.</div>
									<h1>:: Breve Hist&oacute;rico</h1>
									<div style="margin: 0in 0in 10pt">O Projeto Mem&oacute;ria Virtual surgiu no contexto do Projeto Mem&oacute;ria Virtual de S&atilde;o Carlos - um projeto de pol&iacute;ticas p&uacute;blicas apoiado pela FAPESP (processo N. 03/06434-0, vig&ecirc;ncia: abril de 2004 a maio de 2008) - que abordou a informatiza&ccedil;&atilde;o dos acervos hist&oacute;ricos da regi&atilde;o da cidade de S&atilde;o Carlos, visando a possibilitar o acesso, organiza&ccedil;&atilde;o e preserva&ccedil;&atilde;o do patrim&ocirc;nio hist&oacute;rico e cultural das fazendas e museus da regi&atilde;o, integrando e disponibilizando, assim, acervos do munic&iacute;pio dispersos geograficamente. A coordena&ccedil;&atilde;o do projeto foi realizada por pesquisadores do Instituto de Ci&ecirc;ncias Matem&aacute;ticas e de Computa&ccedil;&atilde;o da Universidade de S&atilde;o Paulo (ICMC/USP). O projeto teve natureza multidisciplinar e envolveu tamb&eacute;m a Universidade Federal de S&atilde;o Carlos (UFSCar), a Prefeitura Municipal de S&atilde;o Carlos, o Museu de S&atilde;o Carlos, a Funda&ccedil;&atilde;o Pr&oacute;-Mem&oacute;ria de S&atilde;o Carlos e a Fazenda Pinhal, bem como pesquisadores de diferentes &aacute;reas, tais como a Ci&ecirc;ncias de Computa&ccedil;&atilde;o, Ci&ecirc;ncia da Informa&ccedil;&atilde;o, Biblioteconomia, Arquitetura e Museologia.&nbsp;</div>
									<div style="margin: 0in 0in 10pt">O desenvolvimento do Sistema Mem&oacute;ria Virtual contou ainda com diversos alunos de gradua&ccedil;&atilde;o dos cursos de Computa&ccedil;&atilde;o do ICMC/USP, bem como com pesquisadores de outras &aacute;reas de pesquisa que contribu&iacute;ram para a concep&ccedil;&atilde;o do sistema.&nbsp;</div>
									<div style="margin: 0in 0in 10pt">Atualmente, o Sistema Mem&oacute;ria Virtual est&aacute; inserido no contexto do Projeto Patrim&ocirc;nio Cultural Rural Paulista - tamb&eacute;m um projeto de pol&iacute;ticas p&uacute;blicas apoiado pela FAPESP (processo N. 07/55999-1, vig&ecirc;ncia: abril de 2008 a setembro de 2011) e que objetiva o tratamento dos acervos documentais, seja de car&aacute;ter t&eacute;cnico, hist&oacute;rico, educacional e tur&iacute;stico, relativo &agrave;s fazendas hist&oacute;ricas paulistas. Sob a coordena&ccedil;&atilde;o de pesquisadores da UNICAMP e do Centro de Mem&oacute;ria da UNICAMP, esse projeto conta atualmente com pesquisadores de diversas institui&ccedil;&otilde;es, tais como o ICMC/USP, a UFSCar, a Universidade Estadual Paulista (UNESP) e a Associa&ccedil;&atilde;o Fazendas Hist&oacute;ricas Paulistas.</div>
									
<jsp:include page="../config/footer.jsp" />

